# Generated by Django 4.1.2 on 2022-11-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('typeProduit', models.CharField(max_length=120)),
                ('stock', models.IntegerField()),
                ('minimumStock', models.IntegerField()),
                ('enAchat', models.BooleanField(default=False)),
            ],
        ),
    ]
